"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

"""
현재 안됨.
"""
from setuptools import setup

APP = ['hanyang.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
